service: filo-express

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: production  # Set NODE_ENV to production for Lambda
    MY_EMAIL: ${env:MY_EMAIL}
    MY_PASSWORD: ${env:MY_PASSWORD}
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS}

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

package:
  exclude:
    - .env
    - .env.production
    - .env.development

plugins:
  - serverless-offline
